name: hello world workflow

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  hello:
    runs_on:ubuntu-latest
    steps:
      -uses:action/checkout@v2
      -name:hello world
       run: echo "hello world"
       shell: bash 

  goodbye:
    runs_on:ubuntu-latest
    steps:
      -name: goodbye world
       run:echo "goodbye"
       shell: bash 

